### ISSUE TITLE
Causes Splatoon To Crash

### ISSUE THREAD

**Issue by TumnusB** [Maschell/hid_to_vpad#15]
I got into splatoon (digital) once with it enabled, but everytime after the game on launch freezes and causes me to have to hard shutdown the WIIU i was using a DS4 Default settings

**Comment by Maschell** [comment]
Can you check if it's fixed with 0.9g?

**Comment by wabosh** [comment]
When I start Binding of Isaac: Rebirth, the Wii U also crashes. I'm using the latest stable release version (0.9g). 
I think these two (or maybe more) games force hid_to_vpad to exit which freezes the whole WiiU. When i use the Network Application to connect a gamepad, the game runs smoothly, but the gamepad doesn't work and instead of connected, the button is labeled with reconnecting.

**Comment by Maschell** [comment]
Other people reported that the random crashes reduced with one of the latest nighties.
https://github.com/Maschell/hid_to_vpad/releases/tag/HIDtoVPAD-v0.9g-nightly-e89bfbb
Can you confirm this?

**Comment by wabosh** [comment]
I tried the latest nightly directly after i wrote this, but it didn't work either. It still crashed right after the first splash screen.

**Comment by wabosh** [comment]
https://github.com/Maschell/hid_to_vpad/commit/ec822df6c45f66c2bfdff3346be3b8db195c928a fixed the crash, but it still doesn't work.

**Comment by Maschell** [comment]
Can you check if it's fixed in d450843?

**Comment by wabosh** [comment]
Nothing changed :confused:

**Comment by Maschell** [comment]
Maybe with a2f0008?

**Comment by wabosh** [comment]
It's still the same behaviour like in https://github.com/Maschell/hid_to_vpad/commit/d450843200a11bc9fb55305907a434f037868047

**Comment by Maschell** [comment]
I missed patching one function, now it should work (2872b5e). I also fixed using the network client in  Binding of Isaac: Rebirth.
Can you confirm it's now working?

**Comment by wabosh** [comment]
Yes, it works perfectly, thank you very much.
If there is anything i can help you with, just tell me. I'm not that familar with c++, but i can do some stuff.
